site_name: Strictly Speaking
site_author: Adam Ault
site_url: https://awault.github.io/StrictlySpeaking/

theme:
    name: material
    palette:
        primary: blue grey
        accent: deep orange
    favicon: img/favicon.ico
    logo: img/logo.png
    custom_dir: overrides
    features:
        - navigation.tabs
extra_css:
    - custom.css
markdown_extensions:
    - toc:
        toc_depth: 2
copyright: Copyright &copy; 2023 Adam Ault
extra:
  generator: false
plugins:
  - blogging:
      # GLOBAL CATEGORY: configs for {{ blog_content }}
      dirs:
        - Blog
      template: overrides/custom-blog.html


