site_name: Strictly Speaking
site_author: Adam Ault
site_description: technology, economics and financial markets
site_url: https://awault.github.io/StrictlySpeaking/
repo_name: awault/StrictlySpeaking
repo_url: https://github.com/awault/StrictlySpeaking

edit_uri: ""
copyright: Copyright &copy; 2023 | Strictly Speaking

# Theme
theme:
    name: material
    palette:
        primary: blue grey
        accent: deep orange
    font:
      text: Noto Serif
      code: Roboto Mono
    logo: img/logo.png
    favicon: img/favicon.ico
    features:
      - navigation.tabs
      - navigation.tracking
      - search.suggest
      - search.highlight
      - search.share
    
# Extensions
markdown_extensions:
    - toc:
        toc_depth: 2
    - attr_list # allowed to add HTML attributes and CSS classes

# Plugins
plugins:
  - search
  - mkdocs-jupyter

  - blogging:
      execute: True
      
      # GLOBAL CATEGORY: configs for {{ blog_content }}
      dirs:
        - blog
      template: override/custom-blog.html
            # GLOBAL CONFIG: configs apply to all categories
      time_format: '%m/%d/%Y %H:%M'
      meta_time_format: '%m/%d/%Y %H:%M'
      features:
        tags:
          index_page: tags.md
          insert: top


# Customization
extra:
  social: 
  - icon: fontawesome/brands/github
    link: https://github.com/awault
    name: awault
  - icon: fontawesome/brands/linkedin-in
    link: https://www.linkedin.com/in/awault
    name: Adam Ault
  generator: false # hide the line "Made with Material for MkDocs"

extra_css:
    - assets/extra.css