site_name: Strictly Speaking
site_author: Adam Ault
site_url: https://awault.github.io/StrictlySpeaking/
repo_name: https://github.com/awault/StrictlySpeaking

theme:
    name: material
    palette:
        primary: blue grey
        accent: deep orange
    favicon: img/favicon.ico
    logo: img/logo.png

markdown_extensions:
    - toc:
        toc_depth: 2
copyright: Copyright &copy; 2023 Adam Ault
extra:
  generator: false
plugins:
  - blogging:
      # GLOBAL CATEGORY: configs for {{ blog_content }}
      dirs:
        - blog
      template: override/custom-blog.html
            # GLOBAL CONFIG: configs apply to all categories
      time_format: '%m/%d/%Y %H:%M'
      meta_time_format: '%m/%d/%Y %H:%M'
      features:
        tags:
          index_page: tags.md
          insert: top